import { Link } from 'react-router-dom'
import { PageHero, SectionHead, Reveal } from '../components/ui'
import { Tiers } from '../components/Sections'
const FAQ = [["I'm still in government. Is it too early to start?", "No — it's the best time. Positioning takes weeks, not days, and the leaders who land well start well before their target exit. Direction work is completely confidential."], ['Do you work with military officers as well as federal civilians?', "Yes. Retiring officers and senior NCOs, federal civilians at GS-13 through SES, state and local government leaders, and contractors moving into industry leadership are the core of Amy's practice."], ['Is everything done with Amy personally?', 'Every session, résumé and profile is written and coached by Amy — never handed to an assistant or generated by a template.'], ['How do sessions run?', 'Sessions run online at times that fit your schedule. Documents are delivered in editable Word and PDF formats.'], ['Do you also write SES and federal executive packages?', 'Yes — Amy writes SES résumés, ECQ and TQ narratives for leaders advancing within government. Free samples are in the resource library.']]
export default function Services() {
  return (<main>
    <PageHero crumb="Services" eyebrow="Career & leadership solutions" title={<>Programs built for <em>one transition</em> — yours.</>} lede="Every package is delivered one-to-one by Amy. Start with clarity, add positioning, or take the complete path from direction to offer." />
    <section className="section"><div className="wrap"><Tiers />
      <Reveal as="p" className="tiers-note">Pursuing SES instead of the private sector? Amy also writes SES résumés, ECQs and TQs — <Link to="/contact">ask on a discovery call</Link>, or review the <Link to="/resources#ses">free SES sample materials</Link> first.</Reveal></div></section>
    <section className="section alt"><div className="wrap">
      <SectionHead eyebrow="What you can expect" title="Positioning, not just documents"><p className="lede">Whether you're targeting corporate leadership, consulting, compliance, healthcare administration or operations, the goal is the same: credible, competitive, ready to lead.</p></SectionHead>
      <div className="pillars" style={{ marginTop: 0 }}>
        {[['Résumé & LinkedIn strategy', 'Documents that clearly translate public-sector impact into private-sector value — written by a certified résumé writer, not a template.'], ['Interview preparation', 'Coaching that removes jargon and strengthens executive presence, including a full mock executive interview with feedback.'], ['Structured coaching', 'Accountability, momentum and clarity throughout the transition — with a written plan you can act on the same day.']].map(([h, p], i) => <Reveal key={h} className="pillar" delay={i * .1}><h3>{h}</h3><p>{p}</p></Reveal>)}
      </div></div></section>
    <section className="section"><div className="wrap"><SectionHead eyebrow="Questions" title="Before you book" />
      <Reveal className="faq">{FAQ.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</Reveal></div></section>
  </main>)
}
